### ISSUE TITLE
primary key and

### ISSUE THREAD

**Issue by jamesgaul** [circles-learning-labs/ecto_adapters_dynamodb#21]
Query like this does not work...
query =
        from(
          a in Alert,
          where:
            a.pk == ^pk and fragment("begins_with(?, ?)", a.sk, ^alert_prefix)
        )
      Repo.all(query)

Returns no items but this does return all items where sk begins with alert_prefix string.
query =
        from(
          a in Alert,
          where:
            fragment("begins_with(?, ?)", a.sk, ^alert_prefix)
        )
      Repo.all(query)

**Comment by alhambra1** [comment]
Thank you for contacting us. It looks like the second example in your comment does work? Please see our README for exact examples of our current support for `fragment`. If any of those examples are failing, please let us know. Otherwise, we would be happy to consider ideas as well as pull requests for future features.

**Comment by alhambra1** [comment]
A query like this on a composite global secondary index works for us.

```

q = from(m in Model, where: m.hash_name == HASH_VALUE and fragment("begins_with(?, ?)", m.attribute, ^attribute_value))

Repo.all(q)
```

Are you performing this query on a global secondary index or a composite primary key?

**Comment by jamesgaul** [comment]
Composite primary
On Apr 8, 2019, at 12:06 PM, Gilad Barkan <notifications@github.com<mailto:notifications@github.com>> wrote:


 This message originated outside of DISH and was sent by: noreply@github.com<mailto:noreply@github.com>

A query like this on a composite global secondary index works for us.


q = from(m in Model, where: m.hash_name == HASH_VALUE and fragment("begins_with(?, ?)", m.attribute, ^attribute_value))

Repo.all(q)


Are you performing this query on a global secondary index or a composite primary key?

**Comment by alhambra1** [comment]
We're working on this.

**Comment by alhambra1** [comment]
We've have confirmed and identified this issue and will keep it open, although we don't have a timeframe now for fixing it. Would using a global secondary index for this search be an acceptable workaround? (We've never had a cause to use `begins_with` on a composite primary key since all our primary keys so far have been only hashes.)

We would also consider a pull request should you wish to implement support for this yourself. Please give us at least a week before working on it yourself since we may end up implementing this. The relevant code starts on line 33 in the file, `lib/ecto_adapters_dynamodb/query.ex`. We can see that 

`{hash_values, op} = deep_find_key(search, hd indexes)`

is only looking up the `op` (operator) for the first key of any primary key lookup, neglecting any range key operator. Then we have a simple `if` statement that shows we only especially support the `op`, `:in`, and otherwise default to our most basic primary key query.

**Comment by alhambra1** [comment]
Hi again. It looks like it won't be too bad. We'll try and get to it in the next few days. Thanks again for bringing it to our attention.

**Comment by alhambra1** [comment]
We've updated our GitHub release, extending the support we previously had on global secondary indexes to composite primary keys. Please let us know if you notice anything odd. Thanks again.
